/* #region Backend: catalogo de modelos locales */
export const languageModelCatalog = [
  {
    id: "gemma-4-4b-gguf",
    family: "Gemma 4",
    name: "Gemma 4 4B Instruct GGUF",
    selectorLabel: "Gemma 4 · 4B",
    requestedSizeLabel: "4B",
    expectedSizeLabel: "Aprox. 2.5 GB",
    quantization: "Q2_K",
    format: "GGUF",
    runtime: "llama.cpp / LM Studio / Ollama (con conversion)",
    sourceLabel: "Hugging Face · tensorblock/gemma-3-4b-it-GGUF",
    sourceUrl: "https://huggingface.co/tensorblock/gemma-3-4b-it-GGUF",
    downloadUrl:
      "https://huggingface.co/tensorblock/gemma-3-4b-it-GGUF/resolve/main/gemma-3-4b-it-Q2_K.gguf?download=true",
    fileName: "gemma-3-4b-it-Q2_K.gguf",
    downloadSupported: true,
    note: "Entrada del selector para la familia Gemma con variante local ligera de 4B.",
  },
  {
    id: "gemma-4-2b-gguf",
    family: "Gemma 4",
    name: "Gemma 4 2B Instruct GGUF",
    selectorLabel: "Gemma 4 · 2B",
    requestedSizeLabel: "2B",
    expectedSizeLabel: "Aprox. 1.7 GB",
    quantization: "Q2_K",
    format: "GGUF",
    runtime: "llama.cpp / LM Studio / Ollama (con conversion)",
    sourceLabel: "Hugging Face · tensorblock/gemma-2-2b-it-GGUF",
    sourceUrl: "https://huggingface.co/tensorblock/gemma-2-2b-it-GGUF",
    downloadUrl:
      "https://huggingface.co/tensorblock/gemma-2-2b-it-GGUF/resolve/main/gemma-2-2b-it-Q2_K.gguf?download=true",
    fileName: "gemma-2-2b-it-Q2_K.gguf",
    downloadSupported: true,
    note: "Entrada alineada con la peticion de 2B para la familia Gemma en formato GGUF.",
  },
  {
    id: "phi-3-5-4b-gguf",
    family: "Phi-3.5",
    name: "Phi-3.5 4B Instruct GGUF",
    selectorLabel: "Phi-3.5 · 4B",
    requestedSizeLabel: "4B",
    expectedSizeLabel: "Aprox. 2.2 GB",
    quantization: "Q2_K",
    format: "GGUF",
    runtime: "llama.cpp / LM Studio / Ollama (con conversion)",
    sourceLabel: "Hugging Face · pytholic/Phi-3.5-mini-instruct-GGUF",
    sourceUrl: "https://huggingface.co/pytholic/Phi-3.5-mini-instruct-GGUF",
    downloadUrl:
      "https://huggingface.co/pytholic/Phi-3.5-mini-instruct-GGUF/resolve/main/phi-3.5-mini-instruct-q2_k.gguf?download=true",
    fileName: "phi-3.5-mini-instruct-q2_k.gguf",
    downloadSupported: true,
    note: "Variante GGUF ligera para probar inferencia local con la familia Phi-3.5.",
  },
  {
    id: "phi-3-5-2b-gguf",
    family: "Phi-3.5",
    name: "Phi-3.5 2B GGUF",
    selectorLabel: "Phi-3.5 · 2B",
    requestedSizeLabel: "2B",
    expectedSizeLabel: "Pendiente",
    quantization: "Por definir",
    format: "GGUF",
    runtime: "llama.cpp / LM Studio / Ollama (con conversion)",
    sourceLabel: "Catalogo pendiente de fuente publica",
    sourceUrl: "https://huggingface.co/models?search=Phi-3.5+GGUF",
    downloadUrl: "",
    fileName: "phi-3.5-2b-placeholder.gguf",
    downloadSupported: false,
    note: "La opcion existe en el selector, pero necesita configurar una fuente publica compatible.",
  },
  {
    id: "qwen-3-5-4b-gguf",
    family: "Qwen 3.5",
    name: "Qwen 3.5 4B Instruct GGUF",
    selectorLabel: "Qwen 3.5 · 4B",
    requestedSizeLabel: "4B",
    expectedSizeLabel: "Aprox. 2.8 GB",
    quantization: "Q4_K_M",
    format: "GGUF",
    runtime: "llama.cpp / LM Studio / Ollama (con conversion)",
    sourceLabel: "Hugging Face · ggml-org/Qwen3-4B-GGUF",
    sourceUrl: "https://huggingface.co/ggml-org/Qwen3-4B-GGUF",
    downloadUrl:
      "https://huggingface.co/ggml-org/Qwen3-4B-GGUF/resolve/main/Qwen3-4B-Q4_K_M.gguf?download=true",
    fileName: "Qwen3-4B-Q4_K_M.gguf",
    downloadSupported: true,
    note: "Variante cuantizada para pruebas locales de la familia Qwen 3.5 en 4B.",
  },
  {
    id: "qwen-3-5-2b-gguf",
    family: "Qwen 3.5",
    name: "Qwen 3.5 2B Instruct GGUF",
    selectorLabel: "Qwen 3.5 · 2B",
    requestedSizeLabel: "2B",
    expectedSizeLabel: "Aprox. 1.9 GB",
    quantization: "Q4_K_M",
    format: "GGUF",
    runtime: "llama.cpp / LM Studio / Ollama (con conversion)",
    sourceLabel: "Hugging Face · ggml-org/Qwen3-1.7B-GGUF",
    sourceUrl: "https://huggingface.co/ggml-org/Qwen3-1.7B-GGUF",
    downloadUrl:
      "https://huggingface.co/ggml-org/Qwen3-1.7B-GGUF/resolve/main/Qwen3-1.7B-Q4_K_M.gguf?download=true",
    fileName: "Qwen3-1.7B-Q4_K_M.gguf",
    downloadSupported: true,
    note: "Entrada aproximada a 2B para pruebas locales ligeras de la familia Qwen 3.5.",
  },
];
/* #endregion Backend: catalogo de modelos locales */
